import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "pt" | "en" | "es";

const translations = {
  pt: {
    nav: {
      exames: "Exames",
      corpoClinico: "Corpo Clínico",
      convenios: "Convênios",
      videos: "Vídeos",
      contato: "Contato",
      menuAriaLabel: "Menu",
      langAriaLabel: "Switch to English",
    },
    hero: {
      location: "Sete Lagoas · Minas Gerais",
      clinicLabel: "Clínica de Ultrassom",
      videoAriaLabel: "Vídeo da Clínica Dra. Morgana Kummer",
      description:
        "Diagnóstico por imagem em ultrassonografia geral, obstétrica e vascular — com precisão técnica e a sensibilidade que cada momento exige.",
      ctaWhatsApp: "Agendar pelo WhatsApp",
      ctaExames: "Conheça os exames",
      preAgendamento: "Faça aqui o seu pré-agendamento",
      badge1: "Laudos no mesmo dia",
      badge2: "Atendimento humanizado",
      badge3: "Equipamentos de última geração",
    },
    quote: {
      label: "Filosofia",
      textBefore: "Transformar o cuidado e a tecnologia em momentos inesquecíveis sempre foi o meu ",
      highlight: "maior sonho",
      textAfter: ".",
    },
    about: {
      label: "Sobre a Clínica",
      titleBefore: "Tecnologia que ",
      titleItalic: "acolhe",
      titleAfter: ".",
      statsNumber: "+50 mil",
      statsLabel: "pacientes atendidos",
      p1: "Referência em ultrassonografia em Sete Lagoas, oferecemos diagnóstico por imagem com rigor técnico e atendimento profundamente humano — em um espaço pensado para que cada paciente se sinta cuidado(a) de verdade.",
      p2before: "Desde ",
      p2year: "2017",
      p2mid: ", já tivemos a alegria de cuidar de ",
      p2highlight: "mais de 50 mil pacientes",
      p2after: " — homens, mulheres e suas famílias — recebendo cada um com escuta atenta e o mesmo cuidado que gostaríamos para os nossos.",
    },
    exams: {
      label: "Exames Disponíveis",
      titleBefore: "Cada exame, um ",
      titleItalic: "cuidado próprio",
      titleAfter: ".",
      description:
        "Procedimentos em equipamento de última geração, com laudo detalhado entregue na hora.",
      categoryNames: {
        "Obstétrico": "Obstétrico",
        "Ginecológico": "Ginecológico",
        "Medicina Interna": "Medicina Interna",
        "Vascular": "Vascular",
        "Tireóide e Cervical": "Tireóide e Cervical",
        "Pediátrico": "Pediátrico",
      } as Record<string, string>,
      categoryDescriptions: {
        "Obstétrico": "Acompanhamento gestacional completo, do primeiro ao último trimestre.",
        "Ginecológico": "Saúde da mulher avaliada com sensibilidade e precisão.",
        "Medicina Interna": "Ultrassonografias gerais para diagnóstico amplo e preciso.",
        "Vascular": "Duplex e Doppler para artérias e veias com leitura precisa do fluxo.",
        "Tireóide e Cervical": "Avaliação detalhada da tireoide, cervical e glândulas salivares.",
        "Pediátrico": "Avaliação completa para pacientes pediátricos.",
      } as Record<string, string>,
      examTitles: {} as Record<string, string>,
    },
    cta: {
      label: "Reserve seu horário",
      titleBefore: "Cuidado começa com uma ",
      titleItalic: "conversa",
      titleAfter: ".",
      description:
        "Agendamento exclusivo via WhatsApp. Respostas rápidas e horários flexíveis para ajustar ao seu momento.",
      button: "Falar agora",
    },
    team: {
      label: "Nossa Equipe",
      titleBefore: "Médicos que fazem a ",
      titleItalic: "diferença",
      titleAfter: ".",
      description:
        "Profissionais especializados, comprometidos com excelência diagnóstica e atendimento humanizado.",
      roles: {
        "Ultrassom Geral, Obstétrico e Medicina Fetal": "Ultrassom Geral, Obstétrico e Medicina Fetal",
        "Ultrassom Geral e Obstétrico": "Ultrassom Geral e Obstétrico",
        "Medicina Fetal e Ecocardiografia": "Medicina Fetal e Ecocardiografia",
        "Ultrassom Pediátrico": "Ultrassom Pediátrico",
        "Ultrassom Vascular": "Ultrassom Vascular",
      } as Record<string, string>,
    },
    convenios: {
      label: "Convênios",
      titleBefore: "Atendemos os ",
      titleItalic: "principais planos",
      titleAfter: ".",
      note: "Também atendemos no formato particular.",
    },
    contact: {
      label: "Contato",
      titleBefore: "Vamos conversar sobre seu ",
      titleItalic: "momento",
      titleAfter: ".",
      addressLabel: "Endereço",
      addressValue: "Rua Cândido Azeredo, 41A — Centro, Sete Lagoas/MG",
      whatsappLabel: "WhatsApp",
      hoursLabel: "Horário de Funcionamento",
      hoursValue: "Segunda a Sexta · 7h — 18h\nSábado · 7h30 — 12h",
      instagramLabel: "Instagram",
      mapsAriaLabel: "Abrir endereço no Google Maps",
      mapTitle: "Localização da Clínica Dra. Morgana Kummer",
      addressShort: "Rua Cândido Azeredo, 41A — Centro",
      openLabel: "Abrir",
    },
    footer: {
      tagline: "Para momentos importantes, cuidados únicos.",
      logoAlt: "Logo Dra. Morgana Kummer",
      copy: "Clínica Dra. Morgana Kummer · Sete Lagoas / MG",
    },
    premium: {
      label: "Atendimento exclusivo",
      titleBefore: "Uma experiência diferenciada com a",
      titleName: "Dra. Morgana",
      description:
        "Ultrassonografia geral e medicina fetal realizadas com precisão técnica, tempo dedicado e a sensibilidade que cada imagem merece.",
      button: "Conheça o atendimento exclusivo",
      buttonAriaLabel: "Conheça o atendimento exclusivo da Dra. Morgana (abre em nova aba)",
    },
    examDetail: {
      breadcrumbHome: "Início",
      breadcrumbExams: "Exames",
      scheduleThisExam: "Agendar este exame",
      viewAllExams: "Ver todos os exames",
      gallery: "Imagens do exame",
      galleryTitle: "O que pode",
      gallerySeen: "ser visto",
      faqLabel: "Perguntas frequentes",
      faqTitle: "Tire suas",
      faqDubts: "dúvidas",
      relatedLabel: "Categoria",
      relatedTitle: "Outros exames",
      relatedText: "relacionados",
      learnMore: "Saiba mais",
      viewAll: "Ver todos",
      indications: "Indicações",
      preparation: "Preparo",
      duration: "Duração",
      whatToBring: "O que levar",
      homeImage: "Imagens do exame",
      faq: "Perguntas frequentes",
      backHome: "Voltar à página inicial",
      scheduleExam: "Pronta para agendar seu",
      scheduleEyebrow: "Agende com tranquilidade",
      scheduleTitle: "Pronta para agendar seu",
      scheduleSubtitle: "Atendimento humanizado, equipamento de ponta e laudo entregue no mesmo dia.",
      responseTime: "Resposta em até 1h em horário comercial",
      homeButton: "Voltar à página inicial",
    },
    patientPortal: {
      eyebrow: "Portal do paciente",
      title: "Como podemos ajudar você hoje?",
      subtitle: "Escolha uma das opções abaixo.",
      badgeRecomendado: "Recomendado",
      preAgendamento: "Pré-Agendamento",
      preAgendamentoDesc: "Solicite seu pré-agendamento de forma rápida e prática.",
      preAgendamentoBtnLabel: "Começar",
      preparo: "Preparo para Exames",
      preparoDesc: "Consulte as orientações do seu exame.",
      preparoBtnLabel: "Abrir",
      comoChegar: "Como Chegar",
      comoChegaDesc: "Veja nossa localização e informações para sua visita.",
      comoChegaBtnLabel: "Abrir",
      horarios: "Horário de Funcionamento",
      horariosDesc: "Confira nossos horários de atendimento.",
      horariosBtnLabel: "Ver horários",
      falar: "Falar com a Equipe",
      falarDesc: "Nossa equipe está pronta para ajudar você.",
      falarBtnLabel: "Conversar",
    },
    notFound: {
      title: "Página não encontrada",
      description: "Desculpe, a página que você está procurando não existe.",
      backButton: "Voltar à homepage",
    },
    preparo: {
      title: "Preparo para exames",
      subtitle: "Selecione o exame que você irá realizar.",
      metaLabel: "Leitura: menos de 1 minuto",
      footer: "Essas orientações também serão enviadas novamente pela nossa equipe após a confirmação do agendamento.",
      semPreparo: "Sem preparo especial",
      semPreparoMsg: "Não há preparo especial para este exame. Nossa equipe enviará todas as orientações necessárias pelo WhatsApp após a confirmação do seu agendamento.",
      periodoTitle: "Seu exame será realizado em qual período?",
      periodoDesc: "O preparo varia conforme o horário do exame.",
      manha: "Manhã",
      tarde: "Tarde",
      calloutTitle: "Não encontrou seu exame?",
      calloutDesc: "Nossa equipe pode tirar suas dúvidas e orientar sobre o preparo.",
      calloutCta: "Falar com a nossa equipe",
      whatsappMsg: "Olá! Gostaria de tirar uma dúvida sobre o preparo de um exame.",
    },
    comoChegar: {
      eyebrow: "Como chegar",
      title: "Como chegar à clínica",
      subtitle: "Confira a localização, estacionamento e outras informações importantes antes da sua visita.",
      locationEyebrow: "Localização",
      openMaps: "Abrir no Google Maps",
      mapsUnavailable: "A localização da clínica será disponibilizada em breve.",
      helpCta: "Falar com a nossa equipe",
      whatsappMsg: "Olá! Tenho uma dúvida sobre como chegar à clínica.",
      clinicImage: "Fachada da Clínica Dra. Morgana",
      clinicImageCaption: "Clínica de Ultrassom Dra. Morgana Kummer",
      clinicAddress: "Rua Cândido Azeredo, 41 A\nCentro, Sete Lagoas / MG",
      cards: {
        estacionamento: { titulo: "Estacionamento", descricao: "Há opções de estacionamento próximas à clínica. Toque para ver o mapa.", actionLabel: "Ver mapa" },
        acessibilidade: { titulo: "Acessibilidade", descricao: "Cadeirantes podem acessar a clínica (2º andar) pelo elevador do COE — Centro Odontológico, localizado no andar inferior do mesmo prédio. É necessário entrar pelo COE para utilizar o elevador. Atenção: o elevador não está disponível no horário de almoço." },
        antecedencia: { titulo: "Chegue com antecedência", descricao: "Recomendamos chegar cerca de 15 minutos antes do horário agendado para realizar seu atendimento com tranquilidade." },
        documentos: { titulo: "Documentos", descricao: "No dia do exame, lembre-se de trazer documento de identificação, pedido médico (quando houver) e exames anteriores relacionados." },
        ajuda: { titulo: "Precisa de ajuda?", descricao: "Caso ainda tenha alguma dúvida, nossa equipe terá prazer em ajudar.", actionLabel: "Falar com a nossa equipe" },
      },
    },
    falarSecretaria: {
      eyebrow: "Fale conosco",
      title: "Falar com a secretaria",
      subtitle: "Nossa equipe terá prazer em ajudar você. Selecione o assunto abaixo para iniciar uma conversa pelo WhatsApp.",
      conversarSobre: "Conversar sobre",
      selecionarAssunto: "Selecione um assunto acima",
      ctaPadrao: "Conversar pelo WhatsApp",
      horario: {
        titulo: "Horário de atendimento",
        descricaoPadrao: "Nosso atendimento humano pelo WhatsApp funciona das 08:00 às 11:00 e das 12:30 às 17:30, em dias úteis. Mensagens enviadas fora desse período serão respondidas assim que possível. Lembramos que o pré-agendamento está disponível 24h.",
        mensagens: {
          disponivel: "Atendimento disponível agora.",
          foraHorario: "No momento estamos fora do horário de atendimento. Responderemos assim que possível. O pré-agendamento está disponível 24h.",
        },
      },
    },
    videos: {
      pageTitle: "Vídeos | Clínica Dra. Morgana Kummer",
      eyebrow: "Vídeos",
      title: "Acesse o vídeo do seu ultrassom",
      subtitle: "Área exclusiva para visualizar os vídeos de seus exames.",
      passwordPlaceholder: "Digite a senha recebida...",
      passwordNote: "Para visualização online dos seus exames.",
      accessButton: "Acesse aqui",
      backButton: "Voltar",
    },
    common: {
      close: "Fechar",
      back: "Voltar",
      next: "Próximo",
      skip: "Pular",
      tryAgain: "Tentar novamente",
      chat: "Conversar pelo WhatsApp",
      open: "Abrir",
      error: "Algo deu errado",
      errorMessage: "Não conseguimos registrar suas informações agora. Tente novamente em alguns instantes ou entre em contato pelo WhatsApp.",
      detail: "Detalhe:",
    },
    conversation: {
      menu: {
        title: "Como posso te ajudar?",
        subtitle: "Selecione uma das opções abaixo.",
        option1: "Agendar ultrassom",
        option2: "Como chegar na clínica",
        option3: "Preparo de exames",
        option4: "Outra opção",
      },
      navigation: {
        back: "Voltar",
        next: "Próximo",
        skip: "Pular",
      },
      errors: {
        failedPreAgendamento: "Infelizmente não foi possível finalizar o seu pré-agendamento.",
        tryAgain: "Tentar novamente",
        chatSupport: "Falar pelo WhatsApp",
        returnAndAttachDoc: "Voltar e anexar documento",
      },
      blockedMessages: {
        firstTrimesterNoDoc: "Para agendar um ultrassom obstétrico de 1º trimestre é necessário possuir um pedido médico ou um exame de beta-hCG positivo.",
        noDocOrBetaHCG: "Para agendar um ultrassom é necessário possuir um pedido médico ou um resultado de beta-hCG (no caso de obstétrico de 1º trimestre). Assim que você tiver um desses documentos em mãos, tente novamente ou entre em contato pelo WhatsApp.",
        mustAttachReferral: "Infelizmente, sem o pedido médico não conseguimos concluir o pré-agendamento. Assim que você tiver o pedido em mãos, é só voltar aqui e recomeçar — vai ser rapidinho!",
        mustAttachBetaHCG: "Para finalizar o pré-agendamento é necessário anexar o resultado do beta-hCG. Assim que tiver em mãos, volte e complete o formulário.",
        finalNoDoc: "Infelizmente, sem o pedido médico não conseguimos concluir o pré-agendamento. Assim que você tiver o pedido em mãos, é só voltar aqui e recomeçar — vai ser rapidinho!",
        fallback: "Para agendar um ultrassom obstétrico, precisamos de pelo menos um destes documentos: pedido médico ou resultado do exame de beta-HCG (no caso de gestação inicial). Assim que tiver um desses documentos em mãos, entre em contato diretamente com nossa equipe pelo WhatsApp.",
      },
    },
    uploadArea: {
      tapToSelect: "Toque aqui pra selecionar",
      uploading: "Enviando…",
      optional: "Opcional. ",
      hint: "PDF, JPG ou PNG, máx. 10 MB.",
      fileTooLarge: "Arquivo muito grande. Máximo 10 MB.",
      unexpectedError: "Erro inesperado ao enviar o arquivo.",
      uploadErrorRLS: "Não foi possível enviar o arquivo agora. Você pode finalizar o pré-agendamento e nossa equipe entrará em contato pelo WhatsApp para receber o pedido.",
      uploadErrorGeneric: "Não foi possível enviar o arquivo",
      noReferralButton: "Falar com a equipe",
      fileLabel: "Arquivo",
    },
    businessHours: {
      titulo: "Horário de funcionamento",
      subtitulo: "Confira nossos horários de atendimento.",
      botaoPrimario: {
        label: "Agendar",
      },
      botaoSecundario: {
        label: "Voltar",
      },
      observacao: "Estamos de segunda a sexta das 7h às 18h, sábados de 7h30 às 12h.",
    },
  },
  en: {
    nav: {
      exames: "Exams",
      corpoClinico: "Medical Team",
      convenios: "Health Plans",
      videos: "Videos",
      contato: "Contact",
      menuAriaLabel: "Menu",
      langAriaLabel: "Mudar para Português",
    },
    hero: {
      location: "Sete Lagoas · Minas Gerais",
      clinicLabel: "Ultrasound Clinic",
      videoAriaLabel: "Video of Dr. Morgana Kummer Clinic",
      description:
        "Diagnostic imaging in obstetric, fetal and vascular ultrasound — with technical precision and the sensitivity each unique moment deserves.",
      ctaWhatsApp: "Book via WhatsApp",
      ctaExames: "View exams",
      preAgendamento: "Book your appointment here",
      badge1: "Same-day reports",
      badge2: "Humanised care",
      badge3: "State-of-the-art equipment",
    },
    quote: {
      label: "Philosophy",
      textBefore:
        "Turning care and technology into unforgettable moments has always been my ",
      highlight: "greatest dream",
      textAfter: ".",
    },
    about: {
      label: "About the Clinic",
      titleBefore: "Technology that ",
      titleItalic: "embraces",
      titleAfter: ".",
      statsNumber: "+50k",
      statsLabel: "patients seen",
      p1: "A reference in ultrasound in Sete Lagoas, we offer diagnostic imaging with technical rigour and deeply human care — in a space designed so that every patient feels truly cared for.",
      p2before: "Since ",
      p2year: "2017",
      p2mid: ", we have had the joy of caring for ",
      p2highlight: "more than 50,000 patients",
      p2after:
        " — men, women and their families — welcoming each one with attentive listening and the same care we would want for our own.",
    },
    exams: {
      label: "Available Exams",
      titleBefore: "Each exam, its own ",
      titleItalic: "care",
      titleAfter: ".",
      description:
        "Procedures performed with state-of-the-art equipment, with a detailed report delivered on the spot.",
      categoryNames: {
        "Obstétrico": "Obstetric",
        "Ginecológico": "Gynaecological",
        "Medicina Interna": "Internal Medicine",
        "Vascular": "Vascular",
        "Tireóide e Cervical": "Thyroid & Cervical",
        "Pediátrico": "Paediatric",
      } as Record<string, string>,
      categoryDescriptions: {
        "Obstétrico": "Complete gestational follow-up from the first to the last trimester.",
        "Ginecológico": "Women's health assessed with sensitivity and precision.",
        "Medicina Interna": "General ultrasounds for broad and accurate diagnosis.",
        "Vascular": "Duplex and Doppler for arteries and veins with precise flow assessment.",
        "Tireóide e Cervical": "Detailed evaluation of the thyroid, cervical region and salivary glands.",
        "Pediátrico": "Comprehensive assessment for paediatric patients.",
      } as Record<string, string>,
      examTitles: {
        "Obstétrico do 1º Trimestre":              "1st Trimester Scan",
        "Obstétrico com Translucência Nucal":       "Nuchal Translucency Scan",
        "Obstétrico com Doppler":                   "Obstetric Doppler",
        "Morfológico do 1º Trimestre":              "1st Trimester Anomaly Scan",
        "Morfológico do 2º Trimestre":              "2nd Trimester Anomaly Scan",
        "Morfológico do 3º Trimestre":              "3rd Trimester Anomaly Scan",
        "Perfil Biofísico Fetal (PBF)":            "Fetal Biophysical Profile (BPP)",
        "Ecocardiograma Fetal":                     "Fetal Echocardiogram",
        "Medida do Colo Uterino (Cervicometria)":  "Cervical Length Measurement",
        "Cerclagem do Colo Uterino":                "Cervical Cerclage",
        "Transvaginal (Endovaginal)":               "Transvaginal (Endovaginal)",
        "Transvaginal 3D":                          "3D Transvaginal",
        "Transvaginal com Doppler":                 "Transvaginal with Doppler",
        "Rastreamento de Ovulação":                 "Ovulation Tracking",
        "Pesquisa de Endometriose Profunda":        "Deep Endometriosis Mapping",
        "Ultrassom Perineal":                       "Perineal Ultrasound",
        "Abdome Total":                             "Full Abdomen",
        "Abdome Superior":                          "Upper Abdomen",
        "Hipocôndrio Direito":                      "Right Upper Quadrant",
        "Rins e Vias Urinárias":                    "Kidneys & Urinary Tract",
        "Pélvico Masculino (Próstata)":             "Male Pelvis (Prostate)",
        "Mamas e Axilas":                           "Breast & Axilla",
        "Pélvico Infantil":                         "Paediatric Pelvis",
        "Partes Moles":                             "Soft Tissues",
        "Duplex Scan dos Membros Inferiores":       "Lower Limb Duplex Scan",
        "Carótidas e Vertebrais":                   "Carotid & Vertebral Arteries",
        "Aorta e Ilíacas":                          "Aorta & Iliac Arteries",
        "Tireóide com Doppler":                     "Thyroid with Doppler",
        "Cervical com Doppler":                     "Cervical with Doppler",
        "Glândulas Salivares":                      "Salivary Glands",
        "Abdominal Total (Pediátrico)":             "Full Abdomen (Paediatric)",
        "Rins e Vias Urinárias (Pediátrico)":       "Kidneys & Urinary Tract (Paediatric)",
        "Transfontanela":                           "Transfontanelle",
      } as Record<string, string>,
    },
    cta: {
      label: "Book your appointment",
      titleBefore: "Care begins with a ",
      titleItalic: "conversation",
      titleAfter: ".",
      description:
        "Exclusive booking via WhatsApp. Quick replies and flexible hours to fit your schedule.",
      button: "Talk now",
    },
    team: {
      label: "Our Team",
      titleBefore: "Doctors who make a ",
      titleItalic: "difference",
      titleAfter: ".",
      description:
        "Specialised professionals committed to diagnostic excellence and humanised care.",
      roles: {
        "Ultrassom Geral, Obstétrico e Medicina Fetal": "General & Obstetric Ultrasound · Fetal Medicine",
        "Ultrassom Geral e Obstétrico": "General & Obstetric Ultrasound",
        "Medicina Fetal e Ecocardiografia": "Fetal Medicine & Echocardiography",
        "Ultrassom Pediátrico": "Paediatric Ultrasound",
        "Ultrassom Vascular": "Vascular Ultrasound",
      } as Record<string, string>,
    },
    convenios: {
      label: "Health Plans",
      titleBefore: "We accept the ",
      titleItalic: "main plans",
      titleAfter: ".",
      note: "We also accept private (self-pay) patients.",
    },
    contact: {
      label: "Contact",
      titleBefore: "Let's talk about your ",
      titleItalic: "moment",
      titleAfter: ".",
      addressLabel: "Address",
      addressValue: "Rua Cândido Azeredo, 41A — Centro, Sete Lagoas/MG",
      whatsappLabel: "WhatsApp",
      hoursLabel: "Opening Hours",
      hoursValue: "Monday – Friday · 7 am – 6 pm\nSaturday · 7:30 am – 12 pm",
      instagramLabel: "Instagram",
      mapsAriaLabel: "Open address in Google Maps",
      mapTitle: "Dr. Morgana Kummer Clinic location",
      addressShort: "Rua Cândido Azeredo, 41A — Centro",
      openLabel: "Open",
    },
    footer: {
      tagline: "For important moments, unique care.",
      logoAlt: "Dr. Morgana Kummer Clinic Logo",
      copy: "Dr. Morgana Kummer Clinic · Sete Lagoas / MG",
    },
    premium: {
      label: "Exclusive care",
      titleBefore: "A unique experience with",
      titleName: "Dr. Morgana",
      description:
        "General ultrasound and fetal medicine performed with technical precision, dedicated time and the sensitivity each image deserves.",
      button: "Discover exclusive care",
      buttonAriaLabel: "Discover exclusive care with Dr. Morgana (opens in new tab)",
    },
    examDetail: {
      breadcrumbHome: "Home",
      breadcrumbExams: "Exams",
      scheduleThisExam: "Schedule this exam",
      viewAllExams: "View all exams",
      gallery: "Exam images",
      galleryTitle: "What can",
      gallerySeen: "be seen",
      faqLabel: "Frequently asked questions",
      faqTitle: "Get your",
      faqDubts: "questions answered",
      relatedLabel: "Category",
      relatedTitle: "Other related",
      relatedText: "exams",
      learnMore: "Learn more",
      viewAll: "View all",
      indications: "Indications",
      preparation: "Preparation",
      duration: "Duration",
      whatToBring: "What to bring",
      homeImage: "Exam images",
      faq: "Frequently asked questions",
      backHome: "Back to home",
      scheduleExam: "Ready to book your",
      scheduleEyebrow: "Book with confidence",
      scheduleTitle: "Ready to book your",
      scheduleSubtitle: "Personalized care, state-of-the-art equipment and results delivered the same day.",
      responseTime: "Response within 1 hour during business hours",
      homeButton: "Back to home",
    },
    patientPortal: {
      eyebrow: "Patient portal",
      title: "How can we help you today?",
      subtitle: "Choose one of the options below.",
      badgeRecomendado: "Recommended",
      preAgendamento: "Pre-Booking",
      preAgendamentoDesc: "Request your pre-booking quickly and easily.",
      preAgendamentoBtnLabel: "Start",
      preparo: "Exam Preparation",
      preparoDesc: "Check your exam guidelines.",
      preparoBtnLabel: "Open",
      comoChegar: "How to Get There",
      comoChegaDesc: "See our location and information for your visit.",
      comoChegaBtnLabel: "Open",
      horarios: "Operating Hours",
      horariosDesc: "Check our service hours.",
      horariosBtnLabel: "View hours",
      falar: "Talk to Our Team",
      falarDesc: "Our team is ready to help you.",
      falarBtnLabel: "Chat",
    },
    notFound: {
      title: "Page not found",
      description: "Sorry, the page you are looking for does not exist.",
      backButton: "Back to homepage",
    },
    preparo: {
      title: "Exam Preparation",
      subtitle: "Select the exam you will perform.",
      metaLabel: "Reading time: less than 1 minute",
      footer: "These guidelines will also be sent again by our team after your booking confirmation.",
      semPreparo: "No special preparation",
      semPreparoMsg: "There is no special preparation for this exam. Our team will send all necessary guidelines via WhatsApp after confirming your booking.",
      periodoTitle: "What time will your exam be performed?",
      periodoDesc: "Preparation varies according to exam time.",
      manha: "Morning",
      tarde: "Afternoon",
      calloutTitle: "Didn't find your exam?",
      calloutDesc: "Our team can answer your questions and guide you on preparation.",
      calloutCta: "Talk to our team",
      whatsappMsg: "Hi! I'd like to ask a question about exam preparation.",
    },
    comoChegar: {
      eyebrow: "How to get there",
      title: "How to get to the clinic",
      subtitle: "Check out the location, parking and other important information before your visit.",
      locationEyebrow: "Location",
      openMaps: "Open in Google Maps",
      mapsUnavailable: "The clinic's location will be available soon.",
      helpCta: "Talk to our team",
      whatsappMsg: "Hi! I have a question about how to get to the clinic.",
      clinicImage: "Facade of Dr. Morgana Clinic",
      clinicImageCaption: "Dr. Morgana Kummer Ultrasound Clinic",
      clinicAddress: "Rua Cândido Azeredo, 41 A\nCentro, Sete Lagoas / MG",
      cards: {
        estacionamento: { titulo: "Parking", descricao: "There are parking options near the clinic. Tap to view the map.", actionLabel: "View map" },
        acessibilidade: { titulo: "Accessibility", descricao: "Wheelchair users can access the clinic (2nd floor) via the COE elevator — Centro Odontológico, located on the ground floor of the same building. You must enter through the COE to use the elevator. Note: the elevator is not available during the lunch break." },
        antecedencia: { titulo: "Arrive early", descricao: "We recommend arriving about 15 minutes before your scheduled appointment to ensure a smooth experience." },
        documentos: { titulo: "Documents", descricao: "On the day of your exam, remember to bring a photo ID, your medical referral (if applicable) and any related previous exams." },
        ajuda: { titulo: "Need help?", descricao: "If you still have any questions, our team will be happy to assist you.", actionLabel: "Talk to our team" },
      },
    },
    falarSecretaria: {
      eyebrow: "Get in touch",
      title: "Talk to the secretary",
      subtitle: "Our team will be happy to help you. Select the subject below to start a conversation via WhatsApp.",
      conversarSobre: "Chat about",
      selecionarAssunto: "Select a topic above",
      ctaPadrao: "Chat via WhatsApp",
      horario: {
        titulo: "Service hours",
        descricaoPadrao: "Our human support via WhatsApp operates from 08:00 to 11:00 and 12:30 to 17:30, on business days. Messages sent outside this period will be answered as soon as possible. We remind you that pre-booking is available 24/7.",
        mensagens: {
          disponivel: "Support available now.",
          foraHorario: "We are currently outside business hours. We will respond as soon as possible. Pre-booking is available 24/7.",
        },
      },
    },
    videos: {
      pageTitle: "Videos | Dr. Morgana Kummer Clinic",
      eyebrow: "Videos",
      title: "Access your ultrasound video",
      subtitle: "Exclusive area to view videos of your exams.",
      passwordPlaceholder: "Enter the password you received...",
      passwordNote: "For online viewing of your exams.",
      accessButton: "Access here",
      backButton: "Back",
    },
    common: {
      close: "Close",
      back: "Back",
      next: "Next",
      skip: "Skip",
      tryAgain: "Try again",
      chat: "Chat via WhatsApp",
      open: "Open",
      error: "Something went wrong",
      errorMessage: "We couldn't register your information right now. Please try again in a few moments or contact us via WhatsApp.",
      detail: "Details:",
    },
    conversation: {
      menu: {
        title: "How can I help you?",
        subtitle: "Select one of the options below.",
        option1: "Book an ultrasound",
        option2: "How to get to the clinic",
        option3: "Exam preparation",
        option4: "Another option",
      },
      navigation: {
        back: "Back",
        next: "Next",
        skip: "Skip",
      },
      errors: {
        failedPreAgendamento: "We couldn't complete the pre-booking",
        tryAgain: "Try again",
        chatSupport: "Chat via WhatsApp",
        returnAndAttachDoc: "Return and attach document",
      },
      blockedMessages: {
        firstTrimesterNoDoc: "To book a 1st trimester obstetric ultrasound you need a medical referral or a positive beta-hCG test.",
        noDocOrBetaHCG: "To book an ultrasound you need a medical referral or a beta-hCG result. Once you have it, contact us via WhatsApp to continue.",
        mustAttachReferral: "A medical referral is required to complete pre-booking. Once you have it, come back and try again.",
        mustAttachBetaHCG: "A beta-hCG result is required to complete pre-booking. Once you have it, come back and finish the form.",
        finalNoDoc: "A medical referral is required to complete pre-booking. Please go back and try again.",
        fallback: "To book an obstetric ultrasound we need at least one of these documents: medical referral or beta-hCG result (for early pregnancy). Once you have one of these, contact our team directly via WhatsApp.",
      },
    },
    uploadArea: {
      tapToSelect: "Tap to select",
      uploading: "Uploading…",
      optional: "Optional. ",
      hint: "PDF, JPG or PNG, max. 10 MB.",
      fileTooLarge: "File too large. Maximum 10 MB.",
      unexpectedError: "Unexpected error uploading file.",
      uploadErrorRLS: "We couldn't upload the file right now. You can finish pre-booking and our team will contact you via WhatsApp to receive the referral.",
      uploadErrorGeneric: "Could not upload file",
      noReferralButton: "Contact our team",
      fileLabel: "File",
    },
    businessHours: {
      titulo: "Business hours",
      subtitulo: "Check our service hours.",
      botaoPrimario: {
        label: "Book",
      },
      botaoSecundario: {
        label: "Back",
      },
      observacao: "We are open Monday to Friday from 7am to 6pm, Saturdays from 7:30am to 12pm.",
    },
  },
  es: {
    nav: {
      exames: "Exámenes",
      corpoClinico: "Equipo Médico",
      convenios: "Planes de Salud",
      videos: "Vídeos",
      contato: "Contacto",
      menuAriaLabel: "Menú",
      langAriaLabel: "Cambiar a Portugués",
    },
    hero: {
      location: "Sete Lagoas · Minas Gerais",
      clinicLabel: "Clínica de Ultrasonido",
      videoAriaLabel: "Vídeo de la Clínica Dra. Morgana Kummer",
      description:
        "Diagnóstico por imagen en ultrasonido general, obstétrico y vascular — con precisión técnica y la sensibilidad que cada momento único merece.",
      ctaWhatsApp: "Reservar por WhatsApp",
      ctaExames: "Ver exámenes",
      preAgendamento: "Reserva tu cita aquí",
      badge1: "Informes el mismo día",
      badge2: "Atención humanizada",
      badge3: "Equipos de última generación",
    },
    quote: {
      label: "Filosofía",
      textBefore:
        "Convertir el cuidado y la tecnología en momentos inolvidables siempre ha sido mi ",
      highlight: "mayor sueño",
      textAfter: ".",
    },
    about: {
      label: "Acerca de la Clínica",
      titleBefore: "Tecnología que ",
      titleItalic: "acoge",
      titleAfter: ".",
      statsNumber: "+50 mil",
      statsLabel: "pacientes atendidos",
      p1: "Referencia en ultrasonido en Sete Lagoas, ofrecemos diagnóstico por imagen con rigor técnico y atención profundamente humana — en un espacio pensado para que cada paciente se sienta verdaderamente cuidado.",
      p2before: "Desde ",
      p2year: "2017",
      p2mid: ", hemos tenido la alegría de cuidar a ",
      p2highlight: "más de 50 mil pacientes",
      p2after:
        " — hombres, mujeres y sus familias — recibiendo a cada uno con escucha atenta y el mismo cuidado que desearíamos para los nuestros.",
    },
    exams: {
      label: "Exámenes Disponibles",
      titleBefore: "Cada examen, un ",
      titleItalic: "cuidado propio",
      titleAfter: ".",
      description:
        "Procedimientos en equipos de última generación, con informe detallado entregado en el momento.",
      categoryNames: {
        "Obstétrico": "Obstétrico",
        "Ginecológico": "Ginecológico",
        "Medicina Interna": "Medicina Interna",
        "Vascular": "Vascular",
        "Tireóide e Cervical": "Tiroides y Cervical",
        "Pediátrico": "Pediátrico",
      } as Record<string, string>,
      categoryDescriptions: {
        "Obstétrico": "Seguimiento gestacional completo, del primer al último trimestre.",
        "Ginecológico": "Salud de la mujer evaluada con sensibilidad y precisión.",
        "Medicina Interna": "Ultrasonidos generales para diagnóstico amplio y preciso.",
        "Vascular": "Duplex y Doppler para arterias y venas con lectura precisa del flujo.",
        "Tireóide e Cervical": "Evaluación detallada de la tiroides, región cervical y glándulas salivales.",
        "Pediátrico": "Evaluación completa para pacientes pediátricos.",
      } as Record<string, string>,
      examTitles: {} as Record<string, string>,
    },
    cta: {
      label: "Reserva tu cita",
      titleBefore: "El cuidado comienza con una ",
      titleItalic: "conversación",
      titleAfter: ".",
      description:
        "Reserva exclusiva por WhatsApp. Respuestas rápidas y horarios flexibles para ajustarse a tu momento.",
      button: "Habla ahora",
    },
    team: {
      label: "Nuestro Equipo",
      titleBefore: "Médicos que hacen la ",
      titleItalic: "diferencia",
      titleAfter: ".",
      description:
        "Profesionales especializados, comprometidos con excelencia diagnóstica y atención humanizada.",
      roles: {
        "Ultrassom Geral, Obstétrico e Medicina Fetal": "Ultrasonido General, Obstétrico y Medicina Fetal",
        "Ultrassom Geral e Obstétrico": "Ultrasonido General y Obstétrico",
        "Medicina Fetal e Ecocardiografia": "Medicina Fetal y Ecocardiografía",
        "Ultrassom Pediátrico": "Ultrasonido Pediátrico",
        "Ultrassom Vascular": "Ultrasonido Vascular",
      } as Record<string, string>,
    },
    convenios: {
      label: "Planes de Salud",
      titleBefore: "Aceptamos los ",
      titleItalic: "principales planes",
      titleAfter: ".",
      note: "También atendemos en formato particular.",
    },
    contact: {
      label: "Contacto",
      titleBefore: "Hablemos sobre tu ",
      titleItalic: "momento",
      titleAfter: ".",
      addressLabel: "Dirección",
      addressValue: "Rua Cândido Azeredo, 41A — Centro, Sete Lagoas/MG",
      whatsappLabel: "WhatsApp",
      hoursLabel: "Horario de Funcionamiento",
      hoursValue: "Lunes a Viernes · 7h — 18h\nSábado · 7h30 — 12h",
      instagramLabel: "Instagram",
      mapsAriaLabel: "Abrir dirección en Google Maps",
      mapTitle: "Ubicación de la Clínica Dra. Morgana Kummer",
      addressShort: "Rua Cândido Azeredo, 41A — Centro",
      openLabel: "Abrir",
    },
    footer: {
      tagline: "Para momentos importantes, cuidados únicos.",
      logoAlt: "Logo Clínica Dra. Morgana Kummer",
      copy: "Clínica Dra. Morgana Kummer · Sete Lagoas / MG",
    },
    premium: {
      label: "Atención exclusiva",
      titleBefore: "Una experiencia diferenciada con la",
      titleName: "Dra. Morgana",
      description:
        "Ultrasonido general y medicina fetal realizados con precisión técnica, tiempo dedicado y la sensibilidad que cada imagen merece.",
      button: "Descubre la atención exclusiva",
      buttonAriaLabel: "Descubre la atención exclusiva de la Dra. Morgana (abre en nueva pestaña)",
    },
    examDetail: {
      breadcrumbHome: "Inicio",
      breadcrumbExams: "Exámenes",
      scheduleThisExam: "Agendar este examen",
      viewAllExams: "Ver todos los exámenes",
      gallery: "Imágenes del examen",
      galleryTitle: "Lo que se puede",
      gallerySeen: "ver",
      faqLabel: "Preguntas frecuentes",
      faqTitle: "Resuelve tus",
      faqDubts: "dudas",
      relatedLabel: "Categoría",
      relatedTitle: "Otros exámenes",
      relatedText: "relacionados",
      learnMore: "Conoce más",
      viewAll: "Ver todo",
      indications: "Indicaciones",
      preparation: "Preparación",
      duration: "Duración",
      whatToBring: "Qué traer",
      homeImage: "Imágenes del examen",
      faq: "Preguntas frecuentes",
      backHome: "Volver al inicio",
      scheduleExam: "Listo para reservar tu",
      scheduleEyebrow: "Agenda con tranquilidad",
      scheduleTitle: "Lista para reservar tu",
      scheduleSubtitle: "Atención humanizada, equipamiento de punta y resultado entregado el mismo día.",
      responseTime: "Respuesta en hasta 1 hora en horario comercial",
      homeButton: "Volver al inicio",
    },
    patientPortal: {
      eyebrow: "Portal del paciente",
      title: "¿Cómo podemos ayudarte hoy?",
      subtitle: "Elige una de las opciones abajo.",
      badgeRecomendado: "Recomendado",
      preAgendamento: "Pre-Reserva",
      preAgendamentoDesc: "Solicita tu pre-reserva de forma rápida y práctica.",
      preAgendamentoBtnLabel: "Comenzar",
      preparo: "Preparación para Exámenes",
      preparoDesc: "Consulta las orientaciones de tu examen.",
      preparoBtnLabel: "Abrir",
      comoChegar: "Cómo Llegar",
      comoChegaDesc: "Ve nuestra ubicación e información para tu visita.",
      comoChegaBtnLabel: "Abrir",
      horarios: "Horario de Funcionamiento",
      horariosDesc: "Consulta nuestros horarios de atención.",
      horariosBtnLabel: "Ver horarios",
      falar: "Hablar con el Equipo",
      falarDesc: "Nuestro equipo está listo para ayudarte.",
      falarBtnLabel: "Conversar",
    },
    notFound: {
      title: "Página no encontrada",
      description: "Lo sentimos, la página que buscas no existe.",
      backButton: "Volver a la página principal",
    },
    preparo: {
      title: "Preparación para Exámenes",
      subtitle: "Selecciona el examen que realizarás.",
      metaLabel: "Lectura: menos de 1 minuto",
      footer: "Estas orientaciones también serán reenviadas por nuestro equipo después de confirmar tu reserva.",
      semPreparo: "Sin preparación especial",
      semPreparoMsg: "No hay preparación especial para este examen. Nuestro equipo enviará todas las orientaciones necesarias por WhatsApp después de confirmar tu reserva.",
      periodoTitle: "¿En qué período se realizará tu examen?",
      periodoDesc: "La preparación varía según la hora del examen.",
      manha: "Mañana",
      tarde: "Tarde",
      calloutTitle: "¿No encontraste tu examen?",
      calloutDesc: "Nuestro equipo puede resolver tus dudas y orientarte sobre la preparación.",
      calloutCta: "Hablar con nuestro equipo",
      whatsappMsg: "¡Hola! Me gustaría hacer una pregunta sobre la preparación del examen.",
    },
    comoChegar: {
      eyebrow: "Cómo llegar",
      title: "Cómo llegar a la clínica",
      subtitle: "Consulta la ubicación, estacionamiento y otra información importante antes de tu visita.",
      locationEyebrow: "Ubicación",
      openMaps: "Abrir en Google Maps",
      mapsUnavailable: "La ubicación de la clínica estará disponible pronto.",
      helpCta: "Hablar con nuestro equipo",
      whatsappMsg: "¡Hola! Tengo una pregunta sobre cómo llegar a la clínica.",
      clinicImage: "Fachada de la Clínica Dra. Morgana",
      clinicImageCaption: "Clínica de Ultrasonido Dra. Morgana Kummer",
      clinicAddress: "Rua Cândido Azeredo, 41 A\nCentro, Sete Lagoas / MG",
      cards: {
        estacionamento: { titulo: "Estacionamiento", descricao: "Hay opciones de estacionamiento cerca de la clínica. Toca para ver el mapa.", actionLabel: "Ver mapa" },
        acessibilidade: { titulo: "Accesibilidad", descricao: "Las personas en silla de ruedas pueden acceder a la clínica (2.º piso) mediante el ascensor del COE — Centro Odontológico, ubicado en la planta baja del mismo edificio. Es necesario entrar por el COE para usar el ascensor. Atención: el ascensor no está disponible durante el horario de almuerzo." },
        antecedencia: { titulo: "Llegue con anticipación", descricao: "Recomendamos llegar unos 15 minutos antes de la hora programada para realizar tu atención con tranquilidad." },
        documentos: { titulo: "Documentos", descricao: "El día del examen, recuerda traer documento de identificación, orden médica (cuando corresponda) y exámenes anteriores relacionados." },
        ajuda: { titulo: "¿Necesitas ayuda?", descricao: "Si aún tienes alguna duda, nuestro equipo tendrá gusto en ayudarte.", actionLabel: "Hablar con nuestro equipo" },
      },
    },
    falarSecretaria: {
      eyebrow: "Ponte en contacto",
      title: "Hablar con la secretaria",
      subtitle: "Nuestro equipo tendrá gusto en ayudarte. Selecciona el tema abajo para iniciar una conversación por WhatsApp.",
      conversarSobre: "Conversar sobre",
      selecionarAssunto: "Selecciona un tema arriba",
      ctaPadrao: "Conversar por WhatsApp",
      horario: {
        titulo: "Horario de atención",
        descricaoPadrao: "Nuestro soporte humano por WhatsApp funciona de 08:00 a 11:00 y de 12:30 a 17:30, en días hábiles. Los mensajes enviados fuera de este horario serán respondidos lo antes posible. Te recordamos que la pre-reserva está disponible 24/7.",
        mensagens: {
          disponivel: "Atención disponible ahora.",
          foraHorario: "Actualmente estamos fuera del horario de atención. Responderemos lo antes posible. La pre-reserva está disponible 24/7.",
        },
      },
    },
    videos: {
      pageTitle: "Vídeos | Clínica Dra. Morgana Kummer",
      eyebrow: "Vídeos",
      title: "Accede al vídeo de tu ultrasonido",
      subtitle: "Área exclusiva para ver vídeos de tus exámenes.",
      passwordPlaceholder: "Ingresa la contraseña que recibiste...",
      passwordNote: "Para visualización en línea de tus exámenes.",
      accessButton: "Accede aquí",
      backButton: "Atrás",
    },
    common: {
      close: "Cerrar",
      back: "Atrás",
      next: "Siguiente",
      skip: "Saltar",
      tryAgain: "Intentar de nuevo",
      chat: "Conversar por WhatsApp",
      open: "Abrir",
      error: "Algo salió mal",
      errorMessage: "No pudimos registrar tu información en este momento. Intenta de nuevo en unos momentos o contáctanos por WhatsApp.",
      detail: "Detalle:",
    },
    conversation: {
      menu: {
        title: "¿Cómo puedo ayudarte?",
        subtitle: "Selecciona una de las opciones de abajo.",
        option1: "Reservar un ultrasonido",
        option2: "Cómo llegar a la clínica",
        option3: "Preparación de exámenes",
        option4: "Otra opción",
      },
      navigation: {
        back: "Atrás",
        next: "Siguiente",
        skip: "Saltar",
      },
      errors: {
        failedPreAgendamento: "No pudimos completar la pre-reserva",
        tryAgain: "Intentar de nuevo",
        chatSupport: "Conversar por WhatsApp",
        returnAndAttachDoc: "Volver y adjuntar documento",
      },
      blockedMessages: {
        firstTrimesterNoDoc: "Para reservar un ultrasonido obstétrico de 1er trimestre necesitas una solicitud médica o un examen de beta-hCG positivo.",
        noDocOrBetaHCG: "Para reservar un ultrasonido necesitas una solicitud médica o un resultado de beta-hCG. Cuando lo tengas, contáctanos por WhatsApp para continuar.",
        mustAttachReferral: "Para realizar la pre-reserva es obligatorio adjuntar la solicitud médica. Cuando la tengas, vuelve e intenta de nuevo.",
        mustAttachBetaHCG: "Para finalizar la pre-reserva es necesario adjuntar el resultado del beta-hCG. Cuando lo tengas, vuelve y completa el formulario.",
        finalNoDoc: "Para finalizar la pre-reserva es obligatorio adjuntar la solicitud médica. Vuelve e intenta de nuevo.",
        fallback: "Para reservar un ultrasonido obstétrico necesitamos al menos uno de estos documentos: solicitud médica o resultado de beta-hCG (en caso de embarazo inicial). Cuando tengas uno de ellos, contacta directamente a nuestro equipo por WhatsApp.",
      },
    },
    uploadArea: {
      tapToSelect: "Toca para seleccionar",
      uploading: "Enviando…",
      optional: "Opcional. ",
      hint: "PDF, JPG o PNG, máx. 10 MB.",
      fileTooLarge: "Archivo muy grande. Máximo 10 MB.",
      unexpectedError: "Error inesperado al enviar el archivo.",
      uploadErrorRLS: "No pudimos enviar el archivo ahora. Puedes finalizar la pre-reserva y nuestro equipo te contactará por WhatsApp para recibir la solicitud.",
      uploadErrorGeneric: "No fue posible enviar el archivo",
      noReferralButton: "Hablar con el equipo",
      fileLabel: "Archivo",
    },
    businessHours: {
      titulo: "Horario de funcionamiento",
      subtitulo: "Consulta nuestro horario de atención.",
      botaoPrimario: {
        label: "Reservar",
      },
      botaoSecundario: {
        label: "Atrás",
      },
      observacao: "Estamos de lunes a viernes de 7am a 6pm, sábados de 7:30am a 12pm.",
    },
  },
} as const;

export type Translations = typeof translations.pt;

interface LanguageContextValue {
  lang: Lang;
  toggle: () => void;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("site-lang") as Lang) ?? "pt";
  });

  const toggle = () =>
    setLangState((l) => {
      const languages: Lang[] = ["pt", "en", "es"];
      const currentIndex = languages.indexOf(l);
      const next = languages[(currentIndex + 1) % languages.length];
      localStorage.setItem("site-lang", next);
      return next;
    });

  const setLang = (newLang: Lang) => {
    localStorage.setItem("site-lang", newLang);
    setLangState(newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, toggle, setLang, t: translations[lang] as Translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};
